
services:
  postgres:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d hotel_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SECRECT_TOKEN_KEY: ${SECRECT_TOKEN_KEY}
      POSTGRES_DB: hotel_db
    ports:
      #A porta da esquerda é a porta do host (sua máquina), e a da direita é a porta do container (o banco de dados dentro do container).
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql

  app:
    build: .
    container_name: hotel-api
    ports:
      - "8081:8080"
    depends_on:
       postgres:
          condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotel_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}