server.port=8080
spring.application.name=main

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/hotel_db

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.serialization.indent_output=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.main.allow-bean-definition-overriding=true


spring.web.resources.add-mappings=true

logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG
logging.level.com.fasterxml.jackson=DEBUG
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


